# Site settings
name: Parisod Lab
title: Parisod Lab
email: christian.parisod@unifr.ch
description: "The Parisod Lab @ Johns Hopkins University"
baseurl: ""
url: "http://www.parisodlab.github.io "
permalink: /:categories/:title.html

# RSS
rss_path: feeds/
rss_name: rss.xml

# Page Set
pages_list:
  About: '/about'
  Feed: '/atom.xml'

# Build settings
permalink: pretty

#exclude
exclude: ["scripts/", "build.sh", "README.md", ".DS_Store", 'assets/less/', 'parisodlabsite.sublime-project', 'parisodlabsite.sublime-workspace']



